### ISSUE TITLE
Fails to download PNG type photos

### ISSUE THREAD

**Issue by revanorion** [PetrusZ/twitter-media-scraper#1]
Seems like PNG files are not being downloaded correctly from the twitter image server. The resulting file is a 0 byte PNG file in the output.

A 404 is returned when the downloader appends ?format=jpg&name=orig to the tweet image url for PNGs, however JPGs work correctly. Removing this appended query string to the url fixes the issue and both PNG and JPGs are downloaded correctly. 

Example:
https://pbs.twimg.com/media/FdiUS2_WYAA43bR.png
https://pbs.twimg.com/media/FdiUS2_WYAA43bR.png?format=jpg&name=orig

**Comment by PetrusZ** [comment]
Sorry for the late reply, don't know why I missed this issue before. It should be fixed now, can you test it?

**Comment by revanorion** [comment]
Yup all fixed now. Thanks and great tool!
