### ISSUE TITLE
Is this my network issue or the api is not working anymore?

### ISSUE THREAD

**Issue by JiatengSun** [PetrusZ/twitter-media-scraper#8]
tweet.Error: Post \"https://api.twitter.com/1.1/guest/activate.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

**Comment by PetrusZ** [comment]
I think this is your network issue, it ran normally on my server just 2 hours ago.

**Comment by JiatengSun** [comment]
thank you for your reply, i tried gallery-dl instead and it works well with no network issue with the same network setup, weird.
