### ISSUE TITLE
 Update

### ISSUE THREAD

**Issue by immovably0** [PetrusZ/twitter-media-scraper#9]
Hello, can you tell us if an update is planned?
I tried to download it for docker but the configuration file seems incorrect

**Comment by PetrusZ** [comment]
Hi, I updated v0.1.2, and updated the latest docker image too. You can try if it works.

**Comment by immovably0** [comment]
Good morning,
Thanks, it works.
Another question, does this only take images and videos from tweet? Won't you get them in the media section? Doesn't that take private accounts into account as well?

**Comment by PetrusZ** [comment]
Yeah, only images and videos, but as far as I know the media section is all images and videos?

Can't download from private accounts, currently doesn't support login feature.

**Comment by immovably0** [comment]
Hello, I'm sorry, I have difficulty expressing myself. The bot takes photos and videos of tweets. I therefore ask if it is possible to recover those located in the media.

**Comment by PetrusZ** [comment]
What do you mean recover? Do you want to upload those photos and videos to twitter, or something else?

**Comment by immovably0** [comment]
Good morning,
Yes, I follow groups where the photos and videos are mainly in the media part of the account and with your bot, I only get the tweet from them.

**Comment by PetrusZ** [comment]
OK, Can you check the replies of the account? Can you see the missing photos and videos in the replies?

**Comment by immovably0** [comment]
Hello, when I visit the page "https://twitter.com/BBCWorld", the application correctly retrieves the media found there. However, the media on the "https://twitter.com/BBCWorld/media" page are not retrieved. Would it be possible to also retrieve the media present in this "media" section?

**Comment by PetrusZ** [comment]
Hi @QuentinJ54 , I don't exactly understand what you mean, currently all media is from media section, however some media maybe missing because they're in replies.
So I added `with_replies` config in `config.example.yaml` in v0.1.3, it will scrape media from replies too. Don't know if this is you want, but it's only thing I can do.

**Comment by immovably0** [comment]
Good morning,
thanks for your help.
